### ISSUE TITLE
Google Calendar integration

### ISSUE THREAD

**Issue by ghost** [virtual-dev/cardboard#25]
Add support for a Calendar card with Google Calendar integration. Hopefully there's some sort of calendar API.

**Comment by dotlouis** [comment]
Hey, thanks for stopping by.
I'm not sure about this whole service integration thing.
Because I feel like cardboard could be integrated with almost anything in the world. The problem is that it would make the code big and slow. Besides it means that I have to update cards that rely on third party services which could break APIs.
Finally I kind of think it's redundant to implement this sort of things in a new tab page. Chrome notifications, Android/iOS notifications, widgets whatever. People have a lot of ways to check for a calendar appointment.
This new tab page is for Chrome. and this is a "new tab page" not Google Now or a hub for all your services. I want to keep it simple.
Last but not least I'm the only one to update the application and the more cards and services I have to take care of, the slower the updates for a unique experience.
I want to bring to Chrome things that hasn't been done before. And weather, calendar and stuff are not one of them.
So maybe the solution would be to implement a kind of platform to allow people to create and plug in their own cards but I feel it does not belong into the core application.
I hope you understand my view and you can of course comment on that.
