### ISSUE TITLE
More options!

### ISSUE THREAD

**Issue by Stanzilla** [virtual-dev/cardboard#3]
Hey there, I really love your extension. Currently I'm only missing some options like being able to change the width and the amount of items of each container. That would be amazing.

**Comment by Stanzilla** [comment]
Oh and an option to display the bookmarks bar would be nice, too.

**Comment by dotlouis** [comment]
Hey @Stanzilla, I have rewritten the extension from the ground up.
I plan to do something concerning the bookmark bar. You can preview the work from the branch [material](https://github.com/virtual-dev/cardboard/tree/material).
This is probably not the final implementation (actually it's certainly not even close). I want something truly material and that is as simple and not cluttered as possible. I have a few ideas I think will make it really good ;)

Concerning the amount of items of each containers, it's possible but not the priority. For now fixing bug and polishing what's working before adding features. The other downside is I don't want to add a bazillions options (I technically could) because most users would be lost and find it too complicated.
I keep the issue open and will consider your suggestions.

**Comment by Stanzilla** [comment]
Thanks man, appreciate it. If the bookmarks bar comes back and I can have a few more of my top sites accessible I can really see myself using this extension a lot :)

**Comment by dotlouis** [comment]
@Stanzilla ,
v2 is up and the bookmark card have a dedicated tab for all your bookmarks.
Considering the amount of links to show per cards, I'm seeing a lot of people requesting this feature but I want something flexible and well-thought. I don't want to throw-in options that will make the design bloated/crowded.
I want to find the right balance between customisation and automation.
The problem with a lot of customisation is that it's hard to maintain and if you take a feature away people will get mad at you. So I want to be cautious with the options I add.
